// src/vue/App.vue
<template>
  <div>
    <div class="border" :class="{ isDark }">
      <div>This is Vue.js</div>
      <div>
        <button class="button">
          <span>ClickMe!</span>
          <ripple-effect></ripple-effect>
        </button>
      </div>
      <div>
        <x-input
          type="email"
          placeholder="email"
          :value="email"
          @input="email = $event.target.value"
          :class="{'isDark-input': isDark}"
        ></x-input>
      </div>
      <div>
        <x-input
          type="password"
          placeholder="password"
          :value="password"
          @input="password = $event.target.value"
          :class="{'isDark-input': isDark}"
        ></x-input>
      </div>
      <div>
        <x-toggle @change="isDark = !isDark"></x-toggle>
      </div>
      <div>
        <div>{{email}}</div>
        <div>{{password}}</div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      email: "",
      password: "",
      isDark: false
    };
  }
};
</script>

<style scoped>
.border {
  border: 5px solid #50b47f;
}

.isDark {
  background: #333;
  color: white;
}

.isDark-input {
  --color: white;
}
</style>

// src/react/App.tsx
import * as React from "react";

export default () => {
  const [email, setEmail] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [isDark, setIsDark] = React.useState(false);

  const style = {
    border: "5px solid #5ED4F3",
    background: isDark ? "#333" : "white",
    color: isDark ? "white" : "black"
  };

  return (
    <div style={style}>
      <div>This is react</div>
      <div>
        <button className="button">
          <span>ClickMe!</span>
          <ripple-effect />
        </button>
      </div>
      <div>
        <x-input
          type="email"
          placeholder="email"
          value={email}
          style={{ "--color": isDark ? "white" : "black" }}
          onInput={e => setEmail(e.target.value)}
        />
      </div>
      <div>
        <x-input
          type="password"
          placeholder="password"
          value={password}
          style={{ "--color": isDark ? "white" : "black" }}
          onInput={e => setPassword(e.target.value)}
        />
      </div>
      <div>
        <x-toggle onClick={() => setIsDark(!isDark)} defaultChecked={isDark} />
      </div>
      <div>
        <div>{email}</div>
        <div>{password}</div>
      </div>
    </div>
  );
};
